---
name: "GCP OIDC authentication validation"
defaults:
  run:
    shell: bash
on:
  workflow_dispatch:
    inputs:
      project_number:
        description: "Google project number"
        type: number
        required: true
      project_id:
        description: "Google project ID"
        type: string
        required: true
      workload_identity_pool_id:
        description: "Workload Identity Pool ID"
        type: string
        default: github-actions-pool
        required: true
      workload_identity_pool_provider_id:
        description: "Workload Identity Pool Provider ID"
        type: string
        default: github-actions-provider
        required: true
      service_account:
        description: "Service Account Name"
        type: string
        default: github-actions
        required: true
env:
  TF_IN_AUTOMATION: 'true'
jobs:
  check:
    name: Check
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: 'ubuntu-latest'
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        workload_identity_provider: projects/${{ github.event.inputs.project_number }}/locations/global/workloadIdentityPools/${{ github.event.inputs.workload_identity_pool_id }}/providers/${{ github.event.inputs.workload_identity_pool_provider_id }}
        service_account: '${{ github.event.inputs.service_account }}@${{ github.event.inputs.project_id }}.iam.gserviceaccount.com'
        access_token_lifetime: '300s'
    - name: Login to Google Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    - name: gcloud storage ls
      run: gcloud storage ls
